import type { NotifType } from "./graphTypes";

export interface ClassificationResult {
  type: NotifType;
  generatesNotification: boolean;
  isSectorNews: boolean;
  sectorId: string | null;
}

interface Rule {
  type: NotifType;
  keywords: string[];
  headlineOnly?: boolean;
  negativeKeywords?: string[];
  requireTickerInHeadline?: boolean;
  negativeContextKeywords?: string[];
}

// Ordered rules — first match wins.
const RULES: Rule[] = [
  {
    // Analyst action: only fires when a price target is explicitly set/changed.
    // Generic upgrades/downgrades without a target do not qualify.
    type: "analyst",
    keywords: [
      "price target", "target price", "raises target", "lowers target",
      "cuts target", "boosts target", "increases target", "reduces target",
      "initiates coverage", "initiates at", "sets target", "pt of",
      "target to", "target from",
    ],
    headlineOnly: true,
  },
  {
    // Acquisition: company is acquiring or being acquired by another company.
    type: "acquisition",
    keywords: [
      "acquires", "acquired by", "acquisition of", "to acquire", "agrees to buy",
      "takeover bid", "to be acquired", "buyout of", "merger with",
      "buyout", "takeover", "to buy", "deal to acquire",
    ],
    headlineOnly: true,
    negativeKeywords: [
      "decade", "history", "historical", "farewell", "legacy", "era",
      "years", "former", "retired", "retirement", "anniversary", "past",
      "look back", "reminisce", "veteran", "founded", "since", "biography",
      "memoir", "career", "tenure", "stepping down", "steps down",
    ],
  },
  {
    // Delisting: company is being removed from an exchange.
    type: "delisting",
    keywords: [
      "delisting notice", "delist", "delisted from", "faces delisting",
      "received delisting", "delisting warning", "compliance deficiency",
      "below listing standards", "removed from exchange",
    ],
    headlineOnly: true,
  },
  {
    type: "split",
    keywords: ["stock split", "reverse split", "secondary offering", "share offering"],
  },
  {
    // IPO: kept for auto-classification but in practice admin-managed.
    type: "ipo",
    keywords: ["ipo", "initial public offering", "going public"],
    headlineOnly: true,
    requireTickerInHeadline: true,
    negativeKeywords: [
      "invest in", "ahead of", "before", "rival", "competitor", "leading up to",
      "other", "another", "new", "upcoming", "plans", "eyes", "considers", "watch", "target",
      "spacex", "reddit", "stripe", "klarna", "shein", "chime", "databricks",
    ],
    negativeContextKeywords: ["market", "stocks", "investors", "wall street"],
  },
];

// High-signal company-specific keywords that make a "news" article worth a dot.
// These represent material events that can move the stock.
const HIGH_SIGNAL_NEWS: string[] = [
  "fda approval", "fda approved", "fda rejected", "fda rejects", "fda clearance",
  "fda grants", "breakthrough therapy", "orphan drug",
  "class action", "lawsuit filed", "sec charges", "sec investigation", "doj investigation",
  "chapter 11", "bankruptcy protection", "files for bankruptcy", "files bankruptcy",
  "product recall", "safety recall", "voluntary recall",
  "mass layoff", "major layoffs", "job cuts", "workforce reduction",
  "ceo resigns", "ceo fired", "ceo steps down", "ceo departure", "ceo replaced",
  "accounting fraud", "earnings restatement", "restates earnings",
  "going concern", "liquidity crisis", "cash runway",
  "major contract", "wins contract", "awarded contract", "government contract",
  "phase 3", "clinical trial results", "trial data", "pivotal study",
  "sanctions", "export ban", "trade restriction",
  "data breach", "cyberattack", "ransomware",
];

// Note: "earnings" type is intentionally excluded from RULES.
// Earnings notifications are generated by the API from the earnings calendar
// (±2 days around the actual earnings/filing date), not from news headlines.
const NOTIFICATION_TYPES = new Set<NotifType>([
  "analyst", "delisting", "acquisition", "split", "earnings", "ipo",
]);

const SECTOR_SIGNALS: Array<{ id: string; terms: string[] }> = [
  {
    id: "tech",
    terms: [
      "xlk", "ai sector", "semiconductor sector", "chip sector", "tech sector",
      "semiconductor industry", "cloud sector", "ai stocks", "chip stocks",
      "tech stocks", "technology sector", "semiconductor stocks", "information technology sector",
    ],
  },
  {
    id: "energy",
    terms: [
      "xle", "energy sector", "oil prices", "crude oil", "natural gas prices",
      "opec", "oil market", "energy stocks", "oil stocks", "energy industry",
    ],
  },
  {
    id: "health",
    terms: [
      "xlv", "healthcare sector", "pharma sector", "biotech sector",
      "healthcare stocks", "pharmaceutical sector", "drug stocks", "health stocks",
    ],
  },
  {
    id: "finance",
    terms: [
      "xlf", "interest rates", "fed rate", "federal reserve rate",
      "fintech sector", "banking sector", "rate hike", "rate cut",
      "finance sector", "financial sector", "bank stocks", "financials sector",
    ],
  },
  {
    id: "consumer",
    terms: [
      "xly", "consumer sector", "retail sector", "consumer spending",
      "consumer stocks", "retail stocks", "consumer discretionary",
    ],
  },
  {
    id: "industrials",
    terms: [
      "xli", "industrials sector", "defense sector", "aerospace sector",
      "industrial stocks", "defense stocks", "aerospace stocks", "manufacturing sector",
    ],
  },
  {
    id: "consumer-staples",
    terms: [
      "xlp", "consumer staples", "staples sector", "staples stocks",
      "household goods sector", "consumer staples stocks",
    ],
  },
  {
    id: "communication",
    terms: [
      "xlc", "communication sector", "media sector", "telecom sector",
      "communication stocks", "media stocks", "streaming sector",
    ],
  },
  {
    id: "materials",
    terms: [
      "xlb", "materials sector", "mining sector", "materials stocks",
      "commodities sector", "metals sector", "mining stocks",
    ],
  },
  {
    id: "real-estate",
    terms: [
      "xlre", "real estate sector", "reit", "reits", "property sector",
      "real estate stocks", "real estate market",
    ],
  },
  {
    id: "utilities",
    terms: [
      "xlu", "utilities sector", "utility stocks", "power sector",
      "utilities stocks", "electric utilities", "utility companies",
    ],
  },
];

function detectSector(
  headline: string,
  ticker: string,
): { isSectorNews: boolean; sectorId: string | null } {
  const hl  = headline.toLowerCase();
  const sym = ticker.toLowerCase();

  if (hl.includes(sym)) return { isSectorNews: false, sectorId: null };

  for (const { id, terms } of SECTOR_SIGNALS) {
    if (terms.some((t) => hl.includes(t))) {
      return { isSectorNews: true, sectorId: id };
    }
  }
  return { isSectorNews: false, sectorId: null };
}

export function classifyNews(
  headline: string,
  summary: string,
  ticker: string,
): ClassificationResult {
  const hl  = headline.toLowerCase();
  const sm  = summary.toLowerCase();
  const sym = ticker.toLowerCase();

  let type: NotifType = "news";

  for (const rule of RULES) {
    const texts = rule.headlineOnly ? [hl] : [hl, sm];
    if (!texts.some((t) => rule.keywords.some((kw) => t.includes(kw)))) continue;
    if (rule.requireTickerInHeadline && !hl.includes(sym)) continue;
    if (rule.negativeKeywords?.some((nk) => hl.includes(nk))) continue;
    if (rule.negativeContextKeywords?.some((nk) => hl.includes(nk))) continue;
    type = rule.type;
    break;
  }

  // "news" generates a dot only when the headline contains a high-signal keyword
  // indicating a material company-specific event.
  const generatesNotification = type === "news"
    ? HIGH_SIGNAL_NEWS.some((kw) => hl.includes(kw))
    : NOTIFICATION_TYPES.has(type);

  const { isSectorNews, sectorId } = detectSector(headline, ticker);

  return { type, generatesNotification, isSectorNews, sectorId };
}
